### ISSUE TITLE
SwitchStatement is not supported

### ISSUE THREAD

**Issue by RReverser** [js-js/cfg.js#2]
Looks like support for `switch` statements wasn't implemented (at least couldn't find it in code and doesn't work on own examples).

**Comment by RReverser** [comment]
Okay; I see that `try-catch`, `LabeledStatement` and many others are also unsupported and the project is apparently discontinued anyway.

**Comment by indutny** [comment]
@RReverser I'm going to rebuild this project using `json-pipeline` module eventually, so the current form is a bit old indeed and abandoned ineed.

Just out of curiosity, what is your use case?

**Comment by RReverser** [comment]
Yeah, I saw `json-pipeline` and related modules, but, frankly, it wasn't very clear how to used them in conjunction (or, as turns out, as a replacement) of this one.

Can't go into much details at the moment, but I'm doing some very specific control flow JS optimizations which can be done for apparent reasons easier on flat intermediate representation instead of AST. For that, for prototyping, I decided to use fictionally limited version of ESTree where all the control flow statements are degraded to simple flat nodes + internal operations as "calls" (`GOTO`, `CALL`). This allows me to traverse such AST, serialize IR using `escodegen` and so on. For example, following code:

```javascript
try {
	switch (x) {
		case 1:
			A();
			throw 'ERROR';
		default:
			C();
		case 2:
			B();
	}
} catch (e) {
	console.log(e);
}
```

is transformed into

```javascript
var __ERROR, __RESULT, $0, $1, $2, e;
$0 = x;
$2 = $0 === 1;
$1 = !$2;
if ($1)
    GOTO(10);
$1 = A;
CALL($1, undefined);
if (__ERROR)
    GOTO(22);
__ERROR = 'ERROR';
GOTO(22);
GOTO(17);
// 10:
$2 = $0 === 2;
$1 = !$2;
if ($1)
    GOTO(17);
// 13:
$1 = B;
CALL($1, undefined);
if (__ERROR)
    GOTO(22);
GOTO(21);
// 17:
$0 = C;
CALL($0, undefined);
if (__ERROR)
    GOTO(22);
GOTO(13);
// 21:
GOTO(33);
// 22:
$0 = e;
e = __ERROR;
__ERROR = undefined;
$1 = console;
GET_PROPERTY($1, 'log');
if (__ERROR)
    GOTO(33);
$2 = __RESULT;
$1 = e;
CALL($2, $1, $1);
if (__ERROR)
    GOTO(33);
e = $0;
// 33:
;
```

Things I tried to achieve apart from having a very limited set of instructions:
 - explicitly handle `__ERROR` whenever it's possible - used a global state for that
 - insert direct jumps as close to the handlers as possible
 - reuse temporary variables (aka "registers") as soon as they're "released"

Today I came across your module, and figured that there might be some duplication of efforts, as it also converts ESTree AST to a simplified IR, even though some goals slightly differ. I must admit, I had to read those papers you linked as didn't learn SSA and related optimization strategies earlier, but now I see that perhaps SSA form might be even better for me, as it gives more opportunities for easy optimizations.

However, back to the beginning, it seems that this module is discontinued, and doesn't support some control flow statements I already have, and as for `json-pipeline` - I couldn't figure out how to use it to at least consume ESTree and regenerate it back after e.g. dead code elimination. Would appreciate any hints.

**Comment by RReverser** [comment]
Ha, just found a bug thanks to that output above :)

**Comment by RReverser** [comment]
I saw you also have something similar inside of https://github.com/indutny/spoon, and even though it's older, seems to support more (all of the?) ES5 nodes.

**Comment by indutny** [comment]
Still `switch` is not implemented there: https://github.com/indutny/spoon/blob/master/lib/spoon/cfg.js#L1178 ;)

**Comment by RReverser** [comment]
Ah ok :) In the meanwhile, I've changed my implementation to generate smth closer to proper CFG (with blocks that end either in GOTO or conditional GOTO), and it supports switch, so I guess will be moving on from there. Hoped there is some code I could just use.

**Comment by RReverser** [comment]
I see you started working on it again. Is there anything I could possibly help with?

**Comment by indutny** [comment]
@RReverser sure, totally! I'll just have to stub out the skeleton of this thing first. These ES6 scope variables took some time to deal with :)

**Comment by RReverser** [comment]
@indutny Yeah, I decided to completely skip them in my implementation due to some really tricky contexts like function argument defaults. You might want to use https://github.com/estools/escope to simplify things though (as far as I understand, all that you'll need is to assign unique ID to each declaration, and escope already provides list of them, cross-references, etc.).

**Comment by indutny** [comment]
Yikes, where have you been before! :) I have just finished my clone of this.

**Comment by RReverser** [comment]
Ha, well, I was right there in ESTools org :) And don't worry, you're not the first nor the last.

**Comment by RReverser** [comment]
You might still want to go with Escope as it's well-tested in various projects (incl. ESLint).

**Comment by indutny** [comment]
@RReverser thank you for suggestion, I finally got to this 34d6ce7 :) Still lots of work to do...

**Comment by RReverser** [comment]
@indutny Looks good. I'd like to help, but lack of API documentation on `json-pipeline` makes it somewhat hard to understand what separate methods are for / how to use them in custom implementation, how to actually "pipe" between all the stages and so on. If you could provide any tips on that, I'd happily look into it :)

**Comment by RReverser** [comment]
In the meanwhile, pushed my local experiments (ES5 only) to https://github.com/RReverser/cfg.

**Comment by indutny** [comment]
@RReverser relevant code is here : https://github.com/indutny/json-pipeline/blob/master/test/cfg-test.js#L16-L50 . Sorry, there is no documentation at all there!

You may also export pipeline in a [grapviz](http://www.graphviz.org/) format: `pipeline.render({ cfg: true }, 'graphviz')`.

**Comment by RReverser** [comment]
@indutny Well, it was the first thing I looked into :) (as tests can give at least some clue). But devil is in the details - what happens by default when I just build the graph? What are `reindex` / `link` / `verify` doing and what happens if I don't run [some of] them? And the one I mentioned above:

> how to actually "pipe" between all the stages

(how do I pass the code and inject optimizations into various stages, in some all-in-one example)

**Comment by RReverser** [comment]
Sorry if being too annoying with those questions, just trying to figure out the best direction to move on :smile:

**Comment by indutny** [comment]
@RReverser no problem at all!

1. `reindex()` is just a convenience method for assigning numeric ids for the nodes. They are assigned upon creation, but if things are re-ordered - ids may appear out of order in `.render()` output
2. `link()` is used after constructing CFG

Btw, this may be helpful: http://darksi.de/d.sea-of-nodes/

**Comment by indutny** [comment]
Continuing answers:

`verify()` is just a method to verify that the graph is constructed properly.

**Comment by RReverser** [comment]
> but if things are re-ordered

In which cases are they? Like, on optimizations?

> link() is used after constructing CFG

As far as I understand (probably wrong) from https://github.com/indutny/json-pipeline/blob/master/lib/pipeline/cfg/block.js#L73-L89, it's to just link various blocks for the ordered execution? (as in `goto` in the end of the block to the next one)

Also, this question is still not answered but very interesting:

> > how to actually "pipe" between all the stages
> (how do I pass the code and inject optimizations into various stages, in some all-in-one example)

For example, from what we already have in cfg.js, how to perform ssa:load / ssa:store elimination? I doubt serializing to string and parsing back is an answer, but given that pipeline is created with specific mode as constructor argument and doesn't contain `.pipe` or similarly named method, unclear how to move the constructed code through the stages.

**Comment by indutny** [comment]
> In which cases are they? Like, on optimizations?

Yeah, optimizations. Essentially both blocks and operations in them are all nodes in a big graph. This graph can be shuffled, some nodes could be removed and things could be put back together. This is when ids may not appear sequential at all.

In fact, `json-pipeline-scheduler` will most likely reorder any code, so this is essential for testing. Not that essential for any other uses, though.

> As far as I understand (probably wrong) from https://github.com/indutny/json-pipeline/blob/master/lib/pipeline/cfg/block.js#L73-L89, it's to just link various blocks for the ordered execution? (as in goto in the end of the block to the next one)

Blocks are nodes too, the just have these control dependencies that needs to be filled in. The thing is that this `cfg` mode of `json-pipeline` is mostly about UX, so the blocks are linked only later in time, when all information is available (predecessors, successors).

And indeed it is almost the same thing as `goto`. Good catch!

> For example, from what we already have in cfg.js, how to perform ssa:load / ssa:store elimination? I doubt serializing to string and parsing back is an answer, but given that pipeline is created with specific mode as constructor argument and doesn't contain .pipe or similarly named method, unclear how to move the constructed code through the stages.

https://github.com/js-js/ssa.js - this module will eliminate `ssa:load`/`ssa:store` using fancy algorithms :) (not so fancy, rather trivial. just kidding).

The graph is mutable, the things are changed in place, so there is no need to pipe it anywhere.

There is an example: http://bl.ocks.org/indutny/raw/15382c95aa7ab83b6c96/ . I'm afraid it is broken right, because of the caching. Should be fixed in an hour or so.

**Comment by RReverser** [comment]
> https://github.com/js-js/ssa.js - this module will eliminate ssa:load/ssa:store using fancy algorithms :) (not so fancy, rather trivial. just kidding).

> The graph is mutable, the things are changed in place, so there is no need to pipe it anywhere.

I was confused because README suggests `var pipeline = require('json-pipeline').create('dominance');` (I thought it's important for it to be exactly `dominance` and not `cfg`).

So are you saying that those modes are just APIs for how you want to build the graph, but it doesn't matter for the optimization algorithms which one was used?

**Comment by indutny** [comment]
> I was confused because README suggests var pipeline = require('json-pipeline').create('dominance'); (I thought it's important for it to be exactly dominance and not cfg).

Oooh, you are right! It may be required to reconstruct the graph in a form that have `dominance` relationship.

**Comment by RReverser** [comment]
> It may be required to reconstruct the graph in a form that have dominance relationship.

And here we come back to my original question on how to do that :smile:

**Comment by indutny** [comment]
Arrgh, we have to use `dominance` pipeline in a first place.

Btw, here is how it works in `wasm-cfg`: https://github.com/indutny/wasm-cfg/blob/master/lib/wasm-cfg/builder.js

**Comment by indutny** [comment]
I believe that we will eventually need to consider adding the "effect state changes" here too. Though, it may be done a bit later.

**Comment by RReverser** [comment]
That's a bit... demotivating. I hoped there is another library in this collection that transforms CFG graph to dominance. Otherwise, I fail to see what `cfg` mode in `json-pipeline` can be useful for if you can't convert it to the other forms to be consumed by the algorithms.

**Comment by RReverser** [comment]
Just to explain - the reason I'm working initially on mine, and now on this builder, because I want to use something like that for live coding demos in a talk in a month that would explain various representations and optimizations by transforming live JS into various forms, one into another, and showing what we can do with each of them. I imaging that relatively easily doable, and happy to work on the control flow statements for cfg.js, but for now lacking information on how all those pieces will be glued together.

**Comment by indutny** [comment]
@RReverser I guess we can do `dominance` from ground up without any changes to the cfg.js codebase. Further more, it may be the case that dominance graph `parse` method will accept JSON output of cfg `render`.
