### ISSUE TITLE
Potentially incorrect instruction order on property assignment

### ISSUE THREAD

**Issue by RReverser** [js-js/cfg.js#3]
For the following code:

```
a.x = a.y = 10;
```

The following pipeline is generated:
```
i0 = loadGlobal "a"
i1 = loadGlobal "a"
i2 = literal 10
i3 = storeNamedProperty "y", i1, i2
i4 = storeNamedProperty "x", i0, i3
```

However, `a.y` can easily be a setter which modifies global `a`, so such reordering is unsafe.

Instead, something like following should be generated:

```
i0 = loadGlobal "a"
i1 = literal 10
i2 = storeNamedProperty "y", i0, i1
i3 = loadGlobal "a"
i4 = storeNamedProperty "x", i3, i1
```

(note that additionally result of `storeNamedProperty` is ignored in favor of original value, as it doesn't need to participate in the data flow anyway)

**Comment by RReverser** [comment]
Actually I'm wrong, sorry for that :)

**Comment by indutny** [comment]
Heh! :)
