### ISSUE TITLE
RegExp literals are not handled properly

### ISSUE THREAD

**Issue by RReverser** [js-js/cfg.js#6]
Not sure whether should be fixed here or in printing or...?

Example:

```javascript
/x/;
```

Results in:

```
pipeline {
  b0 {
    i0 = literal {}
  }
}
```

On one hand, it looks like a serialization problem (it's likely using `JSON.stringify` which is not supposed to work against regexps), on another hand maybe it requires transformation into actual `RegExp` construction with regexp source as an argument?

**Comment by indutny** [comment]
Yeah, it is using `JSON.stringify` for this. I'm not sure how to mitigate it, perhaps we just need separate literal type for `RegExp`, and pass literal input as object or string.

**Comment by RReverser** [comment]
How about instruction like `regexp "source", "flags"`?

**Comment by indutny** [comment]
@RReverser 👍
